### ISSUE TITLE
Error with Python Install

### ISSUE THREAD

**Issue by princefishthrower** [GRVYDEV/S.A.T.U.R.D.A.Y#20]
Interested in trying this out / tinkering with it on my system, but with the python install step I get:

```shell
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/j1/ydw6655510z_5szr12ptrhn40000gn/T/pip-install-oi62efds/llvmlite_6ee7e6f42e224bccba1d315e951338df/setup.py", line 55, in <module>
          _guard_py_ver()
        File "/private/var/folders/j1/ydw6655510z_5szr12ptrhn40000gn/T/pip-install-oi62efds/llvmlite_6ee7e6f42e224bccba1d315e951338df/setup.py", line 52, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.4; only versions >=3.7,<3.11 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Despite installing python 3.10.11 with `pyenv` I'm still getting this error, think I need to somehow try and nuke 3.11.4 completely from my system (on mac)

**Comment by GRVYDEV** [comment]
Ugh I ran into this as well when I was getting started. You shouldn't need to nuke 3.11 from your system. Make sure you are activating 3.10 in your current shell before trying to install. I believe you run python instead of python3 when using pyenv as well.
